from seven_api.classes.ExtendedEnum import ExtendedEnum


class Endpoint(ExtendedEnum):
    ANALYTICS = '/analytics'
    BALANCE = '/balance'
    CONTACTS = '/contacts'
    GROUPS = '/groups'
    HOOKS = '/hooks'
    JOURNAL = '/journal'
    JOURNAL_INBOUND = f'{JOURNAL}/inbound'
    JOURNAL_OUTBOUND = f'{JOURNAL}/outbound'
    JOURNAL_REPLIES = f'{JOURNAL}/replies'
    JOURNAL_VOICE = f'{JOURNAL}/voice'
    LOOKUP = '/lookup'
    LOOKUP_CNAM = f'{LOOKUP}/cnam'
    LOOKUP_FORMAT = f'{LOOKUP}/format'
    LOOKUP_HLR = f'{LOOKUP}/hlr'
    LOOKUP_MNP = f'{LOOKUP}/mnp'
    LOOKUP_RCS = f'{LOOKUP}/rcs'
    NUMBERS = '/numbers'
    NUMBERS_ACTIVE = f'{NUMBERS}/active'
    NUMBERS_AVAILABLE = f'{NUMBERS}/available'
    NUMBERS_ORDER = f'{NUMBERS}/order'
    PRICING = '/pricing'
    RCS = '/rcs'
    RCS_EVENTS = f'{RCS}/events'
    RCS_MESSAGES = f'{RCS}/messages'
    SMS = '/sms'
    STATUS = '/status'
    SUBACCOUNTS = '/subaccounts'
    VALIDATE_FOR_VOICE = '/validate_for_voice'
    VOICE = '/voice'
